# Generated by Django 5.2 on 2025-04-06 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部署名')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署一覧',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='社員ID')),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=1, verbose_name='性別')),
                ('date_of_birth', models.DateField(verbose_name='生年月日')),
                ('hire_date', models.DateField(verbose_name='入社日')),
                ('status', models.CharField(choices=[('active', '在籍中'), ('inactive', '退職'), ('leave', '休職中')], default='active', max_length=10, verbose_name='在籍状況')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('salary', models.IntegerField(verbose_name='給与')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department', verbose_name='所属部署')),
            ],
            options={
                'verbose_name': '従業員',
                'verbose_name_plural': '従業員一覧',
                'ordering': ['-hire_date'],
            },
        ),
    ]
